---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    root-VM-Mokrane-vmparc8:
      ansible_host: 172.17.0.9
    root-VM-Mokrane-vmparc7:
      ansible_host: 172.17.0.8
    root-VM-Mokrane-vmparc6:
      ansible_host: 172.17.0.7
    root-VM-Mokrane-vmparc5:
      ansible_host: 172.17.0.6
    root-VM-Mokrane-vmparc4:
      ansible_host: 172.17.0.5
    root-VM-Mokrane-vmparc3:
      ansible_host: 172.17.0.4
    root-VM-Mokrane-vmparc2:
      ansible_host: 172.17.0.3
    root-VM-Mokrane-vmparc1:
      ansible_host: 172.17.0.2



