---
- name: "[TEMPLATE]"
  hosts: all
  vars:
    myapp_conf:
      - "buffer = true"
      - "memory = 90mb"
      - "cache = 1G"
      
  tasks:
    - name: "[TEMPLATE] - create directory"
      file:
        path: /tmp/myapp/
        state: directory
        mode: '0755'
        owner: root
 
    - name: "[TEMPLATE] - create template"
      template:
        src: template/myappconf.cfg.j2
        dest: /tmp/myapp/myappconf.cfg
        mode: '0755'
